version: '3.3'

services:

  user-app:
    build: ./users
    ports:
      - 8600:80
    command: ["poetry", "run", "uvicorn", "source.infraestructure.framework.app:app", "--host", "0.0.0.0", "--port", "80"]
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=123456
      - SECRET=D3AAB54D5ADE7F17D4407BD50FD02648AE563BAA64939E49ED938E675240A709
    depends_on:
      - pgdb
    volumes:
      - ./source:/app/source
    restart: always

  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: user
    volumes:
     - ./postgres:/var/lib/postgresql/data
    ports: 
     - 5437:5432

 
  

      






 
    


